#- id: commitHook
#  name: commitHook
#  entry: pre_commit_hooks_matlab/commitHook.sh
#  description: Example shell script commit hook
#  language: script
#- id: commitHook2
#  name: commitHook2
#  entry: commitHook.bat
#  description: Example shell script commit hook
#  language: system
- id: simulink_close_subsystems
  name: simulink_close_subsystems
  entry: simulink_close_subsystems
  description: Close Simulink Subsystems
  language: python
  types: [file]
  files: \.(slx|mdl)$
  args: []
- id: simulink_zoom_subsystems
  name: simulink_zoom_subsystems
  entry: simulink_zoom_subsystems
  description: Zoom Simulink Subsystems to fit Simulink
  language: python
  types: [file]
  files: \.(slx|mdl)$
  args: []
- id: matlab_smart_indent
  name: matlab_smart_indent
  entry: matlab_smart_indent
  description: MATLAB Smart Indent from TidyCode
  language: python
  files: \.m$
  args: []
- id: matlab_justify
  name: matlab_justify
  entry: matlab_justify
  description: MATLAB justify from TidyCode
  language: python
  files: \.m$
  args: []
