- id: commitHook
  name: commitHook
  entry: pre_commit_hooks_matlab/commitHook.sh
  description: Example shell script commit hook
  language: script
- id: close_simulink_subsystems
  name: close_simulink_subsystems
  entry: close_simulink_subsystems
  description: Example Python hook
  language: python